---
abstract: 'serve RDF data from files'
author:
  - 'Jakob Voß'
build_requires:
  HTTP::Request::Common: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-App-RDF-Files
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  HTTP::Date: '0'
  Moo: '0'
  Plack: '0'
  RDF::Trine: '0'
  perl: v5.10.0
resources:
  bugtracker: https://github.com/nichtich/Plack-App-RDF-Files/issues
  homepage: https://github.com/nichtich/Plack-App-RDF-Files
  repository: https://github.com/nichtich/Plack-App-RDF-Files.git
version: '0.10'
x_contributors:
  - 'Jakob Voss <jakob@nichtich.de>'
  - 'Jakob Voss <voss@gbv.de>'
