---
abstract: 'Serve RDF data from files'
author:
  - 'Jakob Voß <voss@gbv.de>'
build_requires:
  HTTP::Message::PSGI: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
  perl: v5.14.1
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-RDF-Files
requires:
  Carp: 0
  Digest::MD5: 0
  Encode: 0
  File::Spec::Functions: 0
  HTTP::Date: 0
  List::Util: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
  RDF::Trine: 0
  RDF::Trine::Iterator::Graph: 0
  RDF::Trine::Model: 0
  RDF::Trine::Parser: 0
  RDF::Trine::Serializer: 0
  Scalar::Util: 0
  URI: 0
  parent: 0
  perl: v5.14.1
version: 0.02
